swagger: "2.0"

info:
  title: "stock service"
  description: "This API provide the recent stock value"
  version: "#VERSION#"

schemes:
  - "http"
produces:
  - "application/json"

paths:
  /companies:
    get:
      summary: "List all followed companies"
      produces:
        - "application/json"
      responses:
        200:
          description: "ok"
          schema:
            type: object
            required:
            - companies
            properties:
              companies:
                type: array
                items:
                  type: string
        402:
          description: "method not allowed"
        500:
          description: "Internal error."

  /stock:
    get:
      summary: "get stocks"
      produces:
        - "application/json"
      parameters:
      - name: label
        in: query
        description: company stock label
        type: string
      responses:
        200:
          description: "ok"
          schema:
            $ref: "#/definitions/stock"
        400:
          description: "bad request"
        404:
          description: "company not found"
        500:
          description: "internal error"

  /stock/{company}:
    post:
      summary: "add a new company to crawler"
      produces:
        - "application/json"
      parameters:
      - name: company
        in: path
        required: true
        type: string
      responses:
        201:
          description: "created"
        400:
          description: "bad request"
        500:
          description: "internal error"

    delete:
      summary: "stop crawling a company"
      parameters:
      - name: company
        in: path
        required: true
        type: string
      responses:
        200:
          description: "ok"
        404:
          description: "company not found"
        500:
          description: "internal error"

  /stocks/{company}:
    get:
      summary: "get daily stock values for a company"
      produces:
        - "application/json"
      parameters:
      - name: company
        in: path
        required: true
        type: string
      responses:
        200:
          description: "ok"
          schema:
            $ref: "#/definitions/stockValues"
        404:
          description: "company not found"

definitions:
  stockValue:
    type: object
    description: stock value and variation of a company
    properties:
      label:
        type: string
        description: company label
      value:
        type: number
        description: value of the stock company
      variation:
        type: number
        description: value of the daily variation of the stock value
      max:
        type: number
        description: maximum value of the day
      min:
        type: number
        description: minimum value of the day

  stock:
    type: object
    description: list of stock values
    properties:
      count:
        type: integer
      values:
        type: array
        items: 
          $ref: "#/definitions/stockValue"

    example:
      count: 2
      values:
        [
          { label: "RNO", value: 20.22, variation: 2.2 },
          { label: "AIR", value: 220.2, variation: 2.2 }
        ]
  
  company:
    type: object
    properties:
      label:
        type: string
        description: stock label 

  stockValues:
    type: object
    properties:
      label:
        type: string
        description: stock label
      count:
        type: integer
        description: number of values
      values:
        type: array
        items:
          type: number


