// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteStockCompanyParams creates a new DeleteStockCompanyParams object
// no default values defined in spec.
func NewDeleteStockCompanyParams() DeleteStockCompanyParams {

	return DeleteStockCompanyParams{}
}

// DeleteStockCompanyParams contains all the bound params for the delete stock company operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteStockCompany
type DeleteStockCompanyParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	Company string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteStockCompanyParams() beforehand.
func (o *DeleteStockCompanyParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCompany, rhkCompany, _ := route.Params.GetOK("company")
	if err := o.bindCompany(rCompany, rhkCompany, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCompany binds and validates parameter Company from path.
func (o *DeleteStockCompanyParams) bindCompany(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Company = raw

	return nil
}
