// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteStockCompanyOKCode is the HTTP code returned for type DeleteStockCompanyOK
const DeleteStockCompanyOKCode int = 200

/*DeleteStockCompanyOK ok

swagger:response deleteStockCompanyOK
*/
type DeleteStockCompanyOK struct {
}

// NewDeleteStockCompanyOK creates DeleteStockCompanyOK with default headers values
func NewDeleteStockCompanyOK() *DeleteStockCompanyOK {

	return &DeleteStockCompanyOK{}
}

// WriteResponse to the client
func (o *DeleteStockCompanyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteStockCompanyNotFoundCode is the HTTP code returned for type DeleteStockCompanyNotFound
const DeleteStockCompanyNotFoundCode int = 404

/*DeleteStockCompanyNotFound company not found

swagger:response deleteStockCompanyNotFound
*/
type DeleteStockCompanyNotFound struct {
}

// NewDeleteStockCompanyNotFound creates DeleteStockCompanyNotFound with default headers values
func NewDeleteStockCompanyNotFound() *DeleteStockCompanyNotFound {

	return &DeleteStockCompanyNotFound{}
}

// WriteResponse to the client
func (o *DeleteStockCompanyNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteStockCompanyInternalServerErrorCode is the HTTP code returned for type DeleteStockCompanyInternalServerError
const DeleteStockCompanyInternalServerErrorCode int = 500

/*DeleteStockCompanyInternalServerError internal error

swagger:response deleteStockCompanyInternalServerError
*/
type DeleteStockCompanyInternalServerError struct {
}

// NewDeleteStockCompanyInternalServerError creates DeleteStockCompanyInternalServerError with default headers values
func NewDeleteStockCompanyInternalServerError() *DeleteStockCompanyInternalServerError {

	return &DeleteStockCompanyInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteStockCompanyInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
