// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetStockParams creates a new GetStockParams object
// no default values defined in spec.
func NewGetStockParams() GetStockParams {

	return GetStockParams{}
}

// GetStockParams contains all the bound params for the get stock operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetStock
type GetStockParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*company stock label
	  In: query
	*/
	Label *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetStockParams() beforehand.
func (o *GetStockParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qLabel, qhkLabel, _ := qs.GetOK("label")
	if err := o.bindLabel(qLabel, qhkLabel, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindLabel binds and validates parameter Label from query.
func (o *GetStockParams) bindLabel(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Label = &raw

	return nil
}
