// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetStocksOKCode is the HTTP code returned for type GetStocksOK
const GetStocksOKCode int = 200

/*GetStocksOK ok

swagger:response getStocksOK
*/
type GetStocksOK struct {

	/*
	  In: Body
	*/
	Payload *GetStocksOKBody `json:"body,omitempty"`
}

// NewGetStocksOK creates GetStocksOK with default headers values
func NewGetStocksOK() *GetStocksOK {

	return &GetStocksOK{}
}

// WithPayload adds the payload to the get stocks o k response
func (o *GetStocksOK) WithPayload(payload *GetStocksOKBody) *GetStocksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get stocks o k response
func (o *GetStocksOK) SetPayload(payload *GetStocksOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStocksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetStocksPaymentRequiredCode is the HTTP code returned for type GetStocksPaymentRequired
const GetStocksPaymentRequiredCode int = 402

/*GetStocksPaymentRequired method not allowed

swagger:response getStocksPaymentRequired
*/
type GetStocksPaymentRequired struct {
}

// NewGetStocksPaymentRequired creates GetStocksPaymentRequired with default headers values
func NewGetStocksPaymentRequired() *GetStocksPaymentRequired {

	return &GetStocksPaymentRequired{}
}

// WriteResponse to the client
func (o *GetStocksPaymentRequired) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(402)
}

// GetStocksInternalServerErrorCode is the HTTP code returned for type GetStocksInternalServerError
const GetStocksInternalServerErrorCode int = 500

/*GetStocksInternalServerError Internal error.

swagger:response getStocksInternalServerError
*/
type GetStocksInternalServerError struct {
}

// NewGetStocksInternalServerError creates GetStocksInternalServerError with default headers values
func NewGetStocksInternalServerError() *GetStocksInternalServerError {

	return &GetStocksInternalServerError{}
}

// WriteResponse to the client
func (o *GetStocksInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
