// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostStockCreatedCode is the HTTP code returned for type PostStockCreated
const PostStockCreatedCode int = 201

/*PostStockCreated created

swagger:response postStockCreated
*/
type PostStockCreated struct {
}

// NewPostStockCreated creates PostStockCreated with default headers values
func NewPostStockCreated() *PostStockCreated {

	return &PostStockCreated{}
}

// WriteResponse to the client
func (o *PostStockCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostStockBadRequestCode is the HTTP code returned for type PostStockBadRequest
const PostStockBadRequestCode int = 400

/*PostStockBadRequest bad request

swagger:response postStockBadRequest
*/
type PostStockBadRequest struct {
}

// NewPostStockBadRequest creates PostStockBadRequest with default headers values
func NewPostStockBadRequest() *PostStockBadRequest {

	return &PostStockBadRequest{}
}

// WriteResponse to the client
func (o *PostStockBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostStockInternalServerErrorCode is the HTTP code returned for type PostStockInternalServerError
const PostStockInternalServerErrorCode int = 500

/*PostStockInternalServerError internal error

swagger:response postStockInternalServerError
*/
type PostStockInternalServerError struct {
}

// NewPostStockInternalServerError creates PostStockInternalServerError with default headers values
func NewPostStockInternalServerError() *PostStockInternalServerError {

	return &PostStockInternalServerError{}
}

// WriteResponse to the client
func (o *PostStockInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
