// Code generated by go-swagger; DO NOT EDIT.

// Package restapi stock service
//
//  This API provide the recent stock value
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.5
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
