// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This API provide the recent stock value",
    "title": "stock service",
    "version": "0.1"
  },
  "paths": {
    "/stocks": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "List all watched .",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "402": {
            "description": "method not allowed"
          },
          "500": {
            "description": "Internal error."
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This API provide the recent stock value",
    "title": "stock service",
    "version": "0.1"
  },
  "paths": {
    "/stocks": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "List all watched .",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "402": {
            "description": "method not allowed"
          },
          "500": {
            "description": "Internal error."
          }
        }
      }
    }
  },
  "definitions": {
    "GetStocksOKBodyTuple0": {
      "type": "object",
      "required": [
        "P0"
      ],
      "properties": {
        "P0": {
          "type": "string"
        }
      }
    }
  }
}`))
}
