// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteStockCompanyReader is a Reader for the DeleteStockCompany structure.
type DeleteStockCompanyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteStockCompanyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteStockCompanyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteStockCompanyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteStockCompanyInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteStockCompanyOK creates a DeleteStockCompanyOK with default headers values
func NewDeleteStockCompanyOK() *DeleteStockCompanyOK {
	return &DeleteStockCompanyOK{}
}

/*DeleteStockCompanyOK handles this case with default header values.

ok
*/
type DeleteStockCompanyOK struct {
}

func (o *DeleteStockCompanyOK) Error() string {
	return fmt.Sprintf("[DELETE /stock/{company}][%d] deleteStockCompanyOK ", 200)
}

func (o *DeleteStockCompanyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteStockCompanyNotFound creates a DeleteStockCompanyNotFound with default headers values
func NewDeleteStockCompanyNotFound() *DeleteStockCompanyNotFound {
	return &DeleteStockCompanyNotFound{}
}

/*DeleteStockCompanyNotFound handles this case with default header values.

company not found
*/
type DeleteStockCompanyNotFound struct {
}

func (o *DeleteStockCompanyNotFound) Error() string {
	return fmt.Sprintf("[DELETE /stock/{company}][%d] deleteStockCompanyNotFound ", 404)
}

func (o *DeleteStockCompanyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteStockCompanyInternalServerError creates a DeleteStockCompanyInternalServerError with default headers values
func NewDeleteStockCompanyInternalServerError() *DeleteStockCompanyInternalServerError {
	return &DeleteStockCompanyInternalServerError{}
}

/*DeleteStockCompanyInternalServerError handles this case with default header values.

internal error
*/
type DeleteStockCompanyInternalServerError struct {
}

func (o *DeleteStockCompanyInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /stock/{company}][%d] deleteStockCompanyInternalServerError ", 500)
}

func (o *DeleteStockCompanyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
