// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStocksParams creates a new GetStocksParams object
// with the default values initialized.
func NewGetStocksParams() *GetStocksParams {

	return &GetStocksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStocksParamsWithTimeout creates a new GetStocksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStocksParamsWithTimeout(timeout time.Duration) *GetStocksParams {

	return &GetStocksParams{

		timeout: timeout,
	}
}

// NewGetStocksParamsWithContext creates a new GetStocksParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStocksParamsWithContext(ctx context.Context) *GetStocksParams {

	return &GetStocksParams{

		Context: ctx,
	}
}

// NewGetStocksParamsWithHTTPClient creates a new GetStocksParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStocksParamsWithHTTPClient(client *http.Client) *GetStocksParams {

	return &GetStocksParams{
		HTTPClient: client,
	}
}

/*GetStocksParams contains all the parameters to send to the API endpoint
for the get stocks operation typically these are written to a http.Request
*/
type GetStocksParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get stocks params
func (o *GetStocksParams) WithTimeout(timeout time.Duration) *GetStocksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stocks params
func (o *GetStocksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stocks params
func (o *GetStocksParams) WithContext(ctx context.Context) *GetStocksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stocks params
func (o *GetStocksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stocks params
func (o *GetStocksParams) WithHTTPClient(client *http.Client) *GetStocksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stocks params
func (o *GetStocksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetStocksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
