// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetCompaniesReader is a Reader for the GetCompanies structure.
type GetCompaniesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCompaniesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCompaniesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 402:
		result := NewGetCompaniesPaymentRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCompaniesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCompaniesOK creates a GetCompaniesOK with default headers values
func NewGetCompaniesOK() *GetCompaniesOK {
	return &GetCompaniesOK{}
}

/*GetCompaniesOK handles this case with default header values.

ok
*/
type GetCompaniesOK struct {
	Payload *GetCompaniesOKBody
}

func (o *GetCompaniesOK) Error() string {
	return fmt.Sprintf("[GET /companies][%d] getCompaniesOK  %+v", 200, o.Payload)
}

func (o *GetCompaniesOK) GetPayload() *GetCompaniesOKBody {
	return o.Payload
}

func (o *GetCompaniesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetCompaniesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCompaniesPaymentRequired creates a GetCompaniesPaymentRequired with default headers values
func NewGetCompaniesPaymentRequired() *GetCompaniesPaymentRequired {
	return &GetCompaniesPaymentRequired{}
}

/*GetCompaniesPaymentRequired handles this case with default header values.

method not allowed
*/
type GetCompaniesPaymentRequired struct {
}

func (o *GetCompaniesPaymentRequired) Error() string {
	return fmt.Sprintf("[GET /companies][%d] getCompaniesPaymentRequired ", 402)
}

func (o *GetCompaniesPaymentRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetCompaniesInternalServerError creates a GetCompaniesInternalServerError with default headers values
func NewGetCompaniesInternalServerError() *GetCompaniesInternalServerError {
	return &GetCompaniesInternalServerError{}
}

/*GetCompaniesInternalServerError handles this case with default header values.

Internal error.
*/
type GetCompaniesInternalServerError struct {
}

func (o *GetCompaniesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /companies][%d] getCompaniesInternalServerError ", 500)
}

func (o *GetCompaniesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetCompaniesOKBody get companies o k body
swagger:model GetCompaniesOKBody
*/
type GetCompaniesOKBody struct {

	// companies
	// Required: true
	Companies []string `json:"companies"`
}

// Validate validates this get companies o k body
func (o *GetCompaniesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCompanies(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCompaniesOKBody) validateCompanies(formats strfmt.Registry) error {

	if err := validate.Required("getCompaniesOK"+"."+"companies", "body", o.Companies); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCompaniesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCompaniesOKBody) UnmarshalBinary(b []byte) error {
	var res GetCompaniesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
