// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCompaniesParams creates a new GetCompaniesParams object
// with the default values initialized.
func NewGetCompaniesParams() *GetCompaniesParams {

	return &GetCompaniesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCompaniesParamsWithTimeout creates a new GetCompaniesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCompaniesParamsWithTimeout(timeout time.Duration) *GetCompaniesParams {

	return &GetCompaniesParams{

		timeout: timeout,
	}
}

// NewGetCompaniesParamsWithContext creates a new GetCompaniesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCompaniesParamsWithContext(ctx context.Context) *GetCompaniesParams {

	return &GetCompaniesParams{

		Context: ctx,
	}
}

// NewGetCompaniesParamsWithHTTPClient creates a new GetCompaniesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCompaniesParamsWithHTTPClient(client *http.Client) *GetCompaniesParams {

	return &GetCompaniesParams{
		HTTPClient: client,
	}
}

/*GetCompaniesParams contains all the parameters to send to the API endpoint
for the get companies operation typically these are written to a http.Request
*/
type GetCompaniesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get companies params
func (o *GetCompaniesParams) WithTimeout(timeout time.Duration) *GetCompaniesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get companies params
func (o *GetCompaniesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get companies params
func (o *GetCompaniesParams) WithContext(ctx context.Context) *GetCompaniesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get companies params
func (o *GetCompaniesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get companies params
func (o *GetCompaniesParams) WithHTTPClient(client *http.Client) *GetCompaniesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get companies params
func (o *GetCompaniesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCompaniesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
