// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStocksCompanyParams creates a new GetStocksCompanyParams object
// with the default values initialized.
func NewGetStocksCompanyParams() *GetStocksCompanyParams {
	var ()
	return &GetStocksCompanyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStocksCompanyParamsWithTimeout creates a new GetStocksCompanyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStocksCompanyParamsWithTimeout(timeout time.Duration) *GetStocksCompanyParams {
	var ()
	return &GetStocksCompanyParams{

		timeout: timeout,
	}
}

// NewGetStocksCompanyParamsWithContext creates a new GetStocksCompanyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStocksCompanyParamsWithContext(ctx context.Context) *GetStocksCompanyParams {
	var ()
	return &GetStocksCompanyParams{

		Context: ctx,
	}
}

// NewGetStocksCompanyParamsWithHTTPClient creates a new GetStocksCompanyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStocksCompanyParamsWithHTTPClient(client *http.Client) *GetStocksCompanyParams {
	var ()
	return &GetStocksCompanyParams{
		HTTPClient: client,
	}
}

/*GetStocksCompanyParams contains all the parameters to send to the API endpoint
for the get stocks company operation typically these are written to a http.Request
*/
type GetStocksCompanyParams struct {

	/*Company*/
	Company string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get stocks company params
func (o *GetStocksCompanyParams) WithTimeout(timeout time.Duration) *GetStocksCompanyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stocks company params
func (o *GetStocksCompanyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stocks company params
func (o *GetStocksCompanyParams) WithContext(ctx context.Context) *GetStocksCompanyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stocks company params
func (o *GetStocksCompanyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stocks company params
func (o *GetStocksCompanyParams) WithHTTPClient(client *http.Client) *GetStocksCompanyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stocks company params
func (o *GetStocksCompanyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCompany adds the company to the get stocks company params
func (o *GetStocksCompanyParams) WithCompany(company string) *GetStocksCompanyParams {
	o.SetCompany(company)
	return o
}

// SetCompany adds the company to the get stocks company params
func (o *GetStocksCompanyParams) SetCompany(company string) {
	o.Company = company
}

// WriteToRequest writes these params to a swagger request
func (o *GetStocksCompanyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param company
	if err := r.SetPathParam("company", o.Company); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
