// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetStocksReader is a Reader for the GetStocks structure.
type GetStocksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStocksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStocksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 402:
		result := NewGetStocksPaymentRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetStocksInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetStocksOK creates a GetStocksOK with default headers values
func NewGetStocksOK() *GetStocksOK {
	return &GetStocksOK{}
}

/*GetStocksOK handles this case with default header values.

ok
*/
type GetStocksOK struct {
	Payload *GetStocksOKBodyTuple0
}

func (o *GetStocksOK) Error() string {
	return fmt.Sprintf("[GET /stocks][%d] getStocksOK  %+v", 200, o.Payload)
}

func (o *GetStocksOK) GetPayload() *GetStocksOKBodyTuple0 {
	return o.Payload
}

func (o *GetStocksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetStocksOKBodyTuple0)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStocksPaymentRequired creates a GetStocksPaymentRequired with default headers values
func NewGetStocksPaymentRequired() *GetStocksPaymentRequired {
	return &GetStocksPaymentRequired{}
}

/*GetStocksPaymentRequired handles this case with default header values.

method not allowed
*/
type GetStocksPaymentRequired struct {
}

func (o *GetStocksPaymentRequired) Error() string {
	return fmt.Sprintf("[GET /stocks][%d] getStocksPaymentRequired ", 402)
}

func (o *GetStocksPaymentRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetStocksInternalServerError creates a GetStocksInternalServerError with default headers values
func NewGetStocksInternalServerError() *GetStocksInternalServerError {
	return &GetStocksInternalServerError{}
}

/*GetStocksInternalServerError handles this case with default header values.

Internal error.
*/
type GetStocksInternalServerError struct {
}

func (o *GetStocksInternalServerError) Error() string {
	return fmt.Sprintf("[GET /stocks][%d] getStocksInternalServerError ", 500)
}

func (o *GetStocksInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetStocksOKBodyTuple0 GetStocksOKBodyTuple0 a representation of an anonymous Tuple type
swagger:model GetStocksOKBodyTuple0
*/
type GetStocksOKBodyTuple0 struct {

	// p0
	// Required: true
	P0 *string `json:"-"` // custom serializer

}

// UnmarshalJSON unmarshals this tuple type from a JSON array
func (o *GetStocksOKBodyTuple0) UnmarshalJSON(raw []byte) error {
	// stage 1, get the array but just the array
	var stage1 []json.RawMessage
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&stage1); err != nil {
		return err
	}

	// stage 2: hydrates struct members with tuple elements
	if len(stage1) > 0 {
		var dataP0 string
		buf = bytes.NewBuffer(stage1[0])
		dec := json.NewDecoder(buf)
		dec.UseNumber()
		if err := dec.Decode(&dataP0); err != nil {
			return err
		}
		o.P0 = &dataP0

	}

	return nil
}

// MarshalJSON marshals this tuple type into a JSON array
func (o GetStocksOKBodyTuple0) MarshalJSON() ([]byte, error) {
	data := []interface{}{
		o.P0,
	}

	return json.Marshal(data)
}

// Validate validates this get stocks o k body tuple0
func (o *GetStocksOKBodyTuple0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateP0(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetStocksOKBodyTuple0) validateP0(formats strfmt.Registry) error {

	if err := validate.Required("P0", "body", o.P0); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetStocksOKBodyTuple0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetStocksOKBodyTuple0) UnmarshalBinary(b []byte) error {
	var res GetStocksOKBodyTuple0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
