// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteStockCompany(params *DeleteStockCompanyParams) (*DeleteStockCompanyOK, error)

	GetStock(params *GetStockParams) (*GetStockOK, error)

	GetStocks(params *GetStocksParams) (*GetStocksOK, error)

	PostStockCompany(params *PostStockCompanyParams) (*PostStockCompanyCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  DeleteStockCompany stops crawling a company
*/
func (a *Client) DeleteStockCompany(params *DeleteStockCompanyParams) (*DeleteStockCompanyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteStockCompanyParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DeleteStockCompany",
		Method:             "DELETE",
		PathPattern:        "/stock/{company}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteStockCompanyReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteStockCompanyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteStockCompany: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetStock gets stocks
*/
func (a *Client) GetStock(params *GetStockParams) (*GetStockOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetStockParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetStock",
		Method:             "GET",
		PathPattern:        "/stock",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetStockReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetStockOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetStock: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetStocks lists all followed companies
*/
func (a *Client) GetStocks(params *GetStocksParams) (*GetStocksOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetStocksParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetStocks",
		Method:             "GET",
		PathPattern:        "/stocks",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetStocksReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetStocksOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetStocks: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostStockCompany adds a new company to crawler
*/
func (a *Client) PostStockCompany(params *PostStockCompanyParams) (*PostStockCompanyCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostStockCompanyParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostStockCompany",
		Method:             "POST",
		PathPattern:        "/stock/{company}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostStockCompanyReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostStockCompanyCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostStockCompany: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
