// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostStockReader is a Reader for the PostStock structure.
type PostStockReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostStockReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostStockCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostStockBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostStockInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostStockCreated creates a PostStockCreated with default headers values
func NewPostStockCreated() *PostStockCreated {
	return &PostStockCreated{}
}

/*PostStockCreated handles this case with default header values.

created
*/
type PostStockCreated struct {
}

func (o *PostStockCreated) Error() string {
	return fmt.Sprintf("[POST /stock][%d] postStockCreated ", 201)
}

func (o *PostStockCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostStockBadRequest creates a PostStockBadRequest with default headers values
func NewPostStockBadRequest() *PostStockBadRequest {
	return &PostStockBadRequest{}
}

/*PostStockBadRequest handles this case with default header values.

bad request
*/
type PostStockBadRequest struct {
}

func (o *PostStockBadRequest) Error() string {
	return fmt.Sprintf("[POST /stock][%d] postStockBadRequest ", 400)
}

func (o *PostStockBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostStockInternalServerError creates a PostStockInternalServerError with default headers values
func NewPostStockInternalServerError() *PostStockInternalServerError {
	return &PostStockInternalServerError{}
}

/*PostStockInternalServerError handles this case with default header values.

internal error
*/
type PostStockInternalServerError struct {
}

func (o *PostStockInternalServerError) Error() string {
	return fmt.Sprintf("[POST /stock][%d] postStockInternalServerError ", 500)
}

func (o *PostStockInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
