// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tupyy/stock/models"
)

// NewPostStockParams creates a new PostStockParams object
// with the default values initialized.
func NewPostStockParams() *PostStockParams {
	var ()
	return &PostStockParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostStockParamsWithTimeout creates a new PostStockParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostStockParamsWithTimeout(timeout time.Duration) *PostStockParams {
	var ()
	return &PostStockParams{

		timeout: timeout,
	}
}

// NewPostStockParamsWithContext creates a new PostStockParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostStockParamsWithContext(ctx context.Context) *PostStockParams {
	var ()
	return &PostStockParams{

		Context: ctx,
	}
}

// NewPostStockParamsWithHTTPClient creates a new PostStockParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostStockParamsWithHTTPClient(client *http.Client) *PostStockParams {
	var ()
	return &PostStockParams{
		HTTPClient: client,
	}
}

/*PostStockParams contains all the parameters to send to the API endpoint
for the post stock operation typically these are written to a http.Request
*/
type PostStockParams struct {

	/*Label*/
	Label *models.Company

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post stock params
func (o *PostStockParams) WithTimeout(timeout time.Duration) *PostStockParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post stock params
func (o *PostStockParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post stock params
func (o *PostStockParams) WithContext(ctx context.Context) *PostStockParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post stock params
func (o *PostStockParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post stock params
func (o *PostStockParams) WithHTTPClient(client *http.Client) *PostStockParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post stock params
func (o *PostStockParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLabel adds the label to the post stock params
func (o *PostStockParams) WithLabel(label *models.Company) *PostStockParams {
	o.SetLabel(label)
	return o
}

// SetLabel adds the label to the post stock params
func (o *PostStockParams) SetLabel(label *models.Company) {
	o.Label = label
}

// WriteToRequest writes these params to a swagger request
func (o *PostStockParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Label != nil {
		if err := r.SetBodyParam(o.Label); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
