// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostStockCompanyReader is a Reader for the PostStockCompany structure.
type PostStockCompanyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostStockCompanyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostStockCompanyCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostStockCompanyBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostStockCompanyInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostStockCompanyCreated creates a PostStockCompanyCreated with default headers values
func NewPostStockCompanyCreated() *PostStockCompanyCreated {
	return &PostStockCompanyCreated{}
}

/*PostStockCompanyCreated handles this case with default header values.

created
*/
type PostStockCompanyCreated struct {
}

func (o *PostStockCompanyCreated) Error() string {
	return fmt.Sprintf("[POST /stock/{company}][%d] postStockCompanyCreated ", 201)
}

func (o *PostStockCompanyCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostStockCompanyBadRequest creates a PostStockCompanyBadRequest with default headers values
func NewPostStockCompanyBadRequest() *PostStockCompanyBadRequest {
	return &PostStockCompanyBadRequest{}
}

/*PostStockCompanyBadRequest handles this case with default header values.

bad request
*/
type PostStockCompanyBadRequest struct {
}

func (o *PostStockCompanyBadRequest) Error() string {
	return fmt.Sprintf("[POST /stock/{company}][%d] postStockCompanyBadRequest ", 400)
}

func (o *PostStockCompanyBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostStockCompanyInternalServerError creates a PostStockCompanyInternalServerError with default headers values
func NewPostStockCompanyInternalServerError() *PostStockCompanyInternalServerError {
	return &PostStockCompanyInternalServerError{}
}

/*PostStockCompanyInternalServerError handles this case with default header values.

internal error
*/
type PostStockCompanyInternalServerError struct {
}

func (o *PostStockCompanyInternalServerError) Error() string {
	return fmt.Sprintf("[POST /stock/{company}][%d] postStockCompanyInternalServerError ", 500)
}

func (o *PostStockCompanyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
